// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0uvErJQ5HKZk1Gd24ZzbVo6PLqAdmjHU',
    appId: '1:48056550707:web:47ea7a4f6c78317a3c6a46',
    messagingSenderId: '48056550707',
    projectId: 'oops-we-got-married',
    authDomain: 'oops-we-got-married.firebaseapp.com',
    storageBucket: 'oops-we-got-married.appspot.com',
    measurementId: 'G-D0Y753VWWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq42v2tztQSvzVwlpp06GEvJJj0S983rg',
    appId: '1:48056550707:android:242d843447f234003c6a46',
    messagingSenderId: '48056550707',
    projectId: 'oops-we-got-married',
    storageBucket: 'oops-we-got-married.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH4VRD5Oy57HXeNKU5y7T7zdb4KLshr10',
    appId: '1:48056550707:ios:dba8b4842027a6283c6a46',
    messagingSenderId: '48056550707',
    projectId: 'oops-we-got-married',
    storageBucket: 'oops-we-got-married.appspot.com',
    iosBundleId: 'com.example.oopsWeGotMarried',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH4VRD5Oy57HXeNKU5y7T7zdb4KLshr10',
    appId: '1:48056550707:ios:a06585f5ec4203033c6a46',
    messagingSenderId: '48056550707',
    projectId: 'oops-we-got-married',
    storageBucket: 'oops-we-got-married.appspot.com',
    iosBundleId: 'com.example.oopsWeGotMarried.RunnerTests',
  );
}
